# Generated by Django 4.2.2 on 2023-07-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Информация для админа')),
                ('number', models.CharField(max_length=250, verbose_name='Номер клиента')),
                ('name_model', models.CharField(max_length=250, verbose_name='Модель гаджета')),
            ],
        ),
    ]
