# Generated by Django 4.2.2 on 2023-07-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_traidins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade_in',
        ),
    ]
