# Generated by Django 4.2.2 on 2023-07-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('titl_basic', models.CharField(max_length=150, verbose_name='Название')),
                ('anons_basic', models.CharField(max_length=250, verbose_name='Анонс')),
                ('text_for_salary', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
