# Generated by Django 4.2.2 on 2023-07-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('for_admin', '0002_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='titl_basic',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='anons_basic',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='text_for_salary',
        ),
    ]
