# Generated by Django 4.2.2 on 2023-07-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_admin', '0003_rename_titl_basic_mymodel_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_with_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images/')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.DeleteModel(
            name='Full_card',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
